### ISSUE TITLE
About the bibtex

### ISSUE THREAD

**Issue by zhenzhiwang** [sallymmx/ActionCLIP#1]
Hi there,

Thank you for sharing your great work. I am wondering whether it is an accepted paper (according to the provided bibtex in readme) or an pre-print paper in arXiv? It seems that I cannot find this paper by searching the information in the bibtex.

**Comment by sallymmx** [comment]
@zhenzhiwang  Sorry that the bibtex in ReadMe is not correct. Our paper is an pre-print paper in arXiv. The bibtex should be:

@misc{wang2021actionclip,
      title={ActionCLIP: A New Paradigm for Video Action Recognition}, 
      author={Mengmeng Wang and Jiazheng Xing and Yong Liu},
      year={2021},
      eprint={2109.08472},
      archivePrefix={arXiv},
      primaryClass={cs.CV}
}
