### ISSUE TITLE
Cannot reproduce results

### ISSUE THREAD

**Issue by angelaaye** [sallymmx/ActionCLIP#11]
Hello, I tried to reproduce the Kinetics 400 results using the config file `k400_test.yaml` and the 32-frame ViT-B/16 model. I get the following results: `Epoch: [DotMap()/DotMap()]: Top1: 81.32102272727273, Top5: 95.90097402597402`. This is slightly lower than the 82.32% and 96.20% provided in the README. Any insights? Thanks.  

Also, do you have code for the 10-clip 3-crop setting used with the best performant model? If I understand properly, this setting achieves 83.8% and 97.1% as reported in the paper, is that correct?

**Comment by sallymmx** [comment]
1. Please use the k400_ft_tem.yaml this config for training.
2.10-clip 3-crop setting achieves 83.8% and 97.1%, you are right.

**Comment by angelaaye** [comment]
Hi, I used the pretrained ViT-B/16 32-frame model provided in the README. Theoretically, that should produce 82.32% and 96.20% but I am unable to get those numbers.

**Comment by MiaSanLei** [comment]
Hi, I tried to reproduce K400 results using `k400_train.yaml` and the 32-frame ViT-B/16 model, and got the top1 result: 82.56% close to the reported one. However, the top5 result: 94.92% is lower than the reported one. I re-trained the 16-frame and 32-frame models under the same settings except the param `num_segments`.  Are there any other parameters that need to be modified？

**Comment by willyfh** [comment]
@MiaSanLei @angelaaye I think you should open a new issue since this issue is already closed.

**Comment by palak-oza** [comment]
Hi Please help me with how to extract frames and How to use the frames.txt...I am confused here as to how to use pre train models only on txt type data, shouldnt we have it for frames?
