### ISSUE TITLE
About TemporalShift_VIT

### ISSUE THREAD

**Issue by dreamerlin** [sallymmx/ActionCLIP#26]
https://github.com/sallymmx/ActionCLIP/blob/master/modules/temporal_shift.py#L73-L75

Does it really work? I run into errors, can you fix it, or it is just un-runable

**Comment by TitaniumOne** [comment]
> https://github.com/sallymmx/ActionCLIP/blob/master/modules/temporal_shift.py#L73-L75
> 
> Does it really work? I run into errors, can you fix it, or it is just un-runable

Hi, I meet the same problem, have you solve it?

**Comment by z-yaz** [comment]
> Hi, I meet the same problem, have you solve it?

me too。 have you solve it?

**Comment by z-yaz** [comment]
> https://github.com/sallymmx/ActionCLIP/blob/master/modules/temporal_shift.py#L73-L75
> 
> Does it really work? I run into errors, can you fix it, or it is just un-runable

> Hi, I meet the same problem, have you solve it?

me too。 have you solve it?
