### ISSUE TITLE
既然在视频分类数据集上训练了temporal transformer，所以zero-shot分类，其实也只是对训练集的class比较好吧

### ISSUE THREAD

**Issue by shoutOutYangJie** [sallymmx/ActionCLIP#3]

**Comment by sallymmx** [comment]
temporal transformer只重在时序建模，zero-shot重点来自于前面的spatial建模和文本的特征编码。

**Comment by gurkirt** [comment]
How can you be certain that it only does temporal modelling since it has trainable parameters?

**Comment by gurkirt** [comment]
Since it has trainable parameters, how can you be sure that it only does temporal modelling?
with MeanP, I get the following results. 
wandb: Run summary:
wandb: top1 0.32762
wandb: top5 3.62399

Can you please explain what is goinf on?
