### ISSUE TITLE
UCF101的微调

### ISSUE THREAD

**Issue by jxrloveyou** [sallymmx/ActionCLIP#32]
可以公布一下accuracy为97的训练好的模型文件么，我尝试在UCF101上微调，结果和97差了好多

**Comment by iranroman** [comment]
I'm having the same problem. I'm using the model loaded on the google drive link, but on UCF101 I only get an accuracy of 70%. Am I missing something? Thanks!

**Comment by sallymmx** [comment]
您好，我是王蒙蒙，您的邮件我已收到，并及时回复。
