### ISSUE TITLE
No train/validation/test list for HMDB51 or Kinetics?

### ISSUE THREAD

**Issue by FransHk** [sallymmx/ActionCLIP#44]
I am looking to reproduce the model results on the HMDB51 dataset but I cannot find the train/test lists that are used in the network, why are **train_rgb_split1.txt** and **val_rgb_split1.txt** missing?

If they are just all original HMDB51 split lists but appended, why is there no test set? There is currently no way to properly reproduce the model results.

**Comment by sallymmx** [comment]
您好，我是王蒙蒙，您的邮件我已收到，并及时回复。

**Comment by FransHk** [comment]
Update: For anyone running into this, the sets are created by running the preprocessing scripts as described here:

https://github.com/open-mmlab/mmaction2/tree/main/tools/data/hmdb51

Have uploaded the splits train/val splits below for anyone looking to skip this particular step. 


[hmdb51_val_split_1_rawframes.txt](https://github.com/sallymmx/ActionCLIP/files/12674943/hmdb51_val_split_1_rawframes.txt)
[hmdb51_val_split_1_videos.txt](https://github.com/sallymmx/ActionCLIP/files/12674945/hmdb51_val_split_1_videos.txt)
[hmdb51_train_split_1_rawframes.txt](https://github.com/sallymmx/ActionCLIP/files/12674946/hmdb51_train_split_1_rawframes.txt)
[hmdb51_train_split_1_videos.txt](https://github.com/sallymmx/ActionCLIP/files/12674942/hmdb51_train_split_1_videos.txt)
